
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/5186b2ab1c6e0cc129ebf6e08625b5c1c275545e_flag_if_job_task_fail
test $? -ne 0 && exit 1



{ source /opt/intel/oneapi/setvars.sh; } 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000019
test $? -ne 0 && exit 1
if [ ! -f 2602fbd74b2006cc905d1857e303072b8893935b_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 2602fbd74b2006cc905d1857e303072b8893935b_task_tag_finished; else echo 1 > $REMOTE_ROOT/5186b2ab1c6e0cc129ebf6e08625b5c1c275545e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000014
test $? -ne 0 && exit 1
if [ ! -f 3c74750e40601e5b57899f77254080a7ddc11c14_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 3c74750e40601e5b57899f77254080a7ddc11c14_task_tag_finished; else echo 1 > $REMOTE_ROOT/5186b2ab1c6e0cc129ebf6e08625b5c1c275545e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000010
test $? -ne 0 && exit 1
if [ ! -f 72c54c0674a4d23385af3f926236d014a70e5582_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 72c54c0674a4d23385af3f926236d014a70e5582_task_tag_finished; else echo 1 > $REMOTE_ROOT/5186b2ab1c6e0cc129ebf6e08625b5c1c275545e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000024
test $? -ne 0 && exit 1
if [ ! -f e2d59c8bc9f112fb2f627209e0ac05a3892c006e_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch e2d59c8bc9f112fb2f627209e0ac05a3892c006e_task_tag_finished; else echo 1 > $REMOTE_ROOT/5186b2ab1c6e0cc129ebf6e08625b5c1c275545e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000027
test $? -ne 0 && exit 1
if [ ! -f 99da81a117b92fd7181a6645c65a30ebdadc2fe2_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 99da81a117b92fd7181a6645c65a30ebdadc2fe2_task_tag_finished; else echo 1 > $REMOTE_ROOT/5186b2ab1c6e0cc129ebf6e08625b5c1c275545e_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 5186b2ab1c6e0cc129ebf6e08625b5c1c275545e_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 5186b2ab1c6e0cc129ebf6e08625b5c1c275545e_job_tag_finished; else exit 1;fi

