
#!/bin/bash -l



REMOTE_ROOT=$(pwd)
echo 0 > $REMOTE_ROOT/7d58e62434f1a0a776e1eea452868d8903210271_flag_if_job_task_fail
test $? -ne 0 && exit 1



{ source /opt/intel/oneapi/setvars.sh; } 




cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000006
test $? -ne 0 && exit 1
if [ ! -f 45b6e49571f0f2a4a1a21377fe51ef8aaddcfb51_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 45b6e49571f0f2a4a1a21377fe51ef8aaddcfb51_task_tag_finished; else echo 1 > $REMOTE_ROOT/7d58e62434f1a0a776e1eea452868d8903210271_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000005
test $? -ne 0 && exit 1
if [ ! -f 72f504fbf0d6e217524f6e1b4a5d7b2edc1fade0_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 72f504fbf0d6e217524f6e1b4a5d7b2edc1fade0_task_tag_finished; else echo 1 > $REMOTE_ROOT/7d58e62434f1a0a776e1eea452868d8903210271_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000012
test $? -ne 0 && exit 1
if [ ! -f b78039d97ebc2e8f1efccb7d2b4756dd1d53484e_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch b78039d97ebc2e8f1efccb7d2b4756dd1d53484e_task_tag_finished; else echo 1 > $REMOTE_ROOT/7d58e62434f1a0a776e1eea452868d8903210271_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000011
test $? -ne 0 && exit 1
if [ ! -f 9ead4ded06c226191055764af0d296161a5124b5_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 9ead4ded06c226191055764af0d296161a5124b5_task_tag_finished; else echo 1 > $REMOTE_ROOT/7d58e62434f1a0a776e1eea452868d8903210271_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd sys-0004-0001/scale-1.000/000015
test $? -ne 0 && exit 1
if [ ! -f 74db809fd4cee458273af315c428583eaa8c3dd4_task_tag_finished ] ;then
   ( mpirun -n 16 vasp_std ) 1>>fp.log 2>>fp.log 
  if test $? -eq 0; then touch 74db809fd4cee458273af315c428583eaa8c3dd4_task_tag_finished; else echo 1 > $REMOTE_ROOT/7d58e62434f1a0a776e1eea452868d8903210271_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 7d58e62434f1a0a776e1eea452868d8903210271_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 7d58e62434f1a0a776e1eea452868d8903210271_job_tag_finished; else exit 1;fi

